import { javascriptLanguage, scopeCompletionSource } from '@codemirror/lang-javascript'
import { phpLanguage } from '@codemirror/lang-php'
import { syntaxTree } from '@codemirror/language'
import type { Completion, CompletionContext, CompletionResult, CompletionSource } from '@codemirror/autocomplete'
import type { EditorState, Extension } from '@codemirror/state'
import type { SyntaxNode } from '@lezer/common'

type FunctionEntry = readonly [name: string, parameters: string, summary?: string]

interface FunctionIndex {
	wordpress: string
	php: string
	functions: {
		wordpress: readonly FunctionEntry[]
		php: readonly FunctionEntry[]
	}
}

const PHP_KEYWORDS = [
	'abstract', 'and', 'array', 'as', 'break', 'callable', 'case', 'catch', 'class', 'clone', 'const', 'continue',
	'declare', 'default', 'do', 'echo', 'else', 'elseif', 'empty', 'enum', 'extends', 'false', 'final', 'finally', 'fn',
	'for', 'foreach', 'function', 'global', 'if', 'implements', 'include', 'include_once', 'instanceof', 'interface',
	'isset', 'list', 'match', 'namespace', 'new', 'null', 'or', 'parent', 'print', 'private', 'protected', 'public',
	'readonly', 'require', 'require_once', 'return', 'self', 'static', 'switch', 'throw', 'trait', 'true', 'try', 'unset',
	'use', 'var', 'while', 'xor', 'yield'
]

const KEYWORD_COMPLETIONS: readonly Completion[] = PHP_KEYWORDS.map(label => ({ label, type: 'keyword' }))

/**
 * Words shorter than this only offer completions when asked for with
 * Ctrl-Space, so that the long function list does not open on every letter.
 */
const MIN_IMPLICIT_WORD_LENGTH = 2

const NON_CODE_NODES = new Set(['String', 'HeredocString', 'LineComment', 'BlockComment'])

const DOCUMENTATION_URLS = {
	wordpress: (name: string) => `https://developer.wordpress.org/reference/functions/${name}/`,
	php: (name: string) => `https://www.php.net/manual/function.${name.replace(/_/g, '-')}.php`
}

let functionCompletions: Promise<readonly Completion[]> | undefined

const renderFunctionInfo = (signature: string, summary: string | undefined, url: string, linkText: string) =>
	(): Node => {
		const info = document.createElement('div')
		info.className = 'cs-completion-info'

		const code = document.createElement('code')
		code.textContent = signature
		info.append(code)

		if (summary) {
			const description = document.createElement('p')
			description.textContent = summary
			info.append(description)
		}

		const link = document.createElement('a')
		link.href = url
		link.target = '_blank'
		link.rel = 'noopener noreferrer'
		link.textContent = linkText
		info.append(link)

		return info
	}

const toFunctionCompletions = (
	entries: readonly FunctionEntry[],
	source: keyof FunctionIndex['functions'],
	linkText: string
): Completion[] =>
	entries.map(([name, parameters, summary]) => ({
		label: name,
		type: 'function',
		detail: 'wordpress' === source ? 'WordPress' : 'PHP',
		info: renderFunctionInfo(`${name}${parameters}`, summary, DOCUMENTATION_URLS[source](name), linkText)
	}))

/**
 * WordPress and PHP functions, generated by `scripts/generate-function-index.php`
 * and loaded the first time they are needed.
 */
const loadFunctionCompletions = (linkText: string): Promise<readonly Completion[]> => {
	functionCompletions ??= import(/* webpackChunkName: "editor-function-index" */ './data/function-index.json')
		.then(module => {
			const { functions } = <FunctionIndex> <unknown> module.default
			return [
				...toFunctionCompletions(functions.wordpress, 'wordpress', linkText),
				...toFunctionCompletions(functions.php, 'php', linkText)
			]
		})
		.catch((error: unknown) => {
			console.error('Could not load the function index.', error)
			functionCompletions = undefined
			return []
		})

	return functionCompletions
}

/**
 * Variables, functions and classes declared in the snippet itself.
 */
const localCompletions = (state: EditorState, excludeFrom: number): { variables: Completion[], names: Completion[] } => {
	const variables = new Map<string, Completion>()
	const names = new Map<string, Completion>()

	syntaxTree(state).iterate({
		enter: node => {
			if ('VariableName' === node.name && node.from !== excludeFrom) {
				const label = state.sliceDoc(node.from, node.to)
				variables.set(label, { label, type: 'variable', boost: 1 })
			} else if ('Name' === node.name) {
				const parent = node.node.parent?.name
				const type = 'FunctionDefinition' === parent ? 'function' : 'ClassDeclaration' === parent && 'class'

				if (type) {
					const label = state.sliceDoc(node.from, node.to)
					names.set(label, { label, type, boost: 1 })
				}
			}
		}
	})

	return { variables: [...variables.values()], names: [...names.values()] }
}

const isInNonCode = (context: CompletionContext): boolean => {
	for (let node: SyntaxNode | null = syntaxTree(context.state).resolveInner(context.pos, -1); node; node = node.parent) {
		if (NON_CODE_NODES.has(node.name)) {
			return true
		}
	}

	return false
}

/**
 * Completions for PHP: variables in scope, then keywords, the snippet's own
 * functions and classes, and WordPress and PHP functions.
 */
export const phpCompletionSource: CompletionSource = async (context): Promise<CompletionResult | null> => {
	const variable = context.matchBefore(/\$\w*/)

	if (variable) {
		const inInterpolation = 'VariableName' === syntaxTree(context.state).resolveInner(context.pos, -1).name
		return isInNonCode(context) && !inInterpolation
			? null
			: { from: variable.from, options: localCompletions(context.state, variable.from).variables, validFor: /^\$\w*$/ }
	}

	const word = context.matchBefore(/\w+/)
	const from = word?.from ?? context.pos

	if (!context.explicit && (!word || word.to - word.from < MIN_IMPLICIT_WORD_LENGTH)) {
		return null
	}

	const line = context.state.doc.lineAt(from)

	// Members of an object or class cannot be known without type information.
	if (isInNonCode(context) || /(?:->|::)\s*$/.test(line.text.slice(0, from - line.from))) {
		return null
	}

	const functions = await loadFunctionCompletions(context.state.phrase('Documentation'))

	return {
		from,
		options: [...KEYWORD_COMPLETIONS, ...localCompletions(context.state, -1).names, ...functions],
		validFor: /^\w*$/
	}
}

/**
 * Completion sources added to the languages' own: PHP, and browser globals in
 * JavaScript. CSS and HTML complete through their language support alone.
 */
export const snippetCompletions: Extension = [
	phpLanguage.data.of({ autocomplete: phpCompletionSource }),
	javascriptLanguage.data.of({ autocomplete: scopeCompletionSource(globalThis) })
]
