<?php

/**
 * This file handles exporting snippets in XML format
 *
 * It's better to call the export_snippets()
 * function than directly using this class
 *
 * @since      1.9
 * @package    Code_Snippets
 * @subpackage Export
 */

if ( ! class_exists( 'Code_Snippets_Export' ) ) :

/**
 * Exports selected snippets to a XML or PHP file.
 *
 * @since  1.3
 * @param  array  $ids    The IDs of the snippets to export
 * @param  string $format The format of the export file
 * @return void
 */
class Code_Snippets_Export {

	/**
	 * The IDs
	 * @var array
	 */
	public $snippet_ids = array();

	/**
	 * The name of the table to fetch snippets from
	 * @var string
	 */
	protected $table_name = '';

	/**
	 * The DOM document
	 * @var object
	 */
	public $dom;

	/**
	 * The DOM document root element
	 * @var object
	 */
	public $root;

	/**
	 * Constructor function
	 * @param array  $ids   The IDs of the snippets to export
	 * @param string $table The name of the table to fetch snippets from
	 */
	function __construct( $ids, $table ) {
		$this->snippet_ids = (array) $ids;
		$this->table_name = $table;
		$this->exclude_fields = apply_filters( 'code_snippets/export/exclude_from_export', array( 'id', 'active' ) );
	}

	/**
	 * Build the export file name
	 * @return string
	 */
	function get_filename() {

		if ( 1 == count( $this->snippet_ids ) ) {
			/* If there is only snippet to export, use its name instead of the site name */
			$snippet  = get_snippet( $this->snippet_ids[0], $this->table_name );
			$sitename = strtolower( $snippet->name );
		} else {
			/* Otherwise, use the site name as set in Settings > General */
			$sitename = strtolower( get_bloginfo( 'name' ) );
		}

		/* Filter and sanitize the filename */
		$filename = sanitize_file_name( apply_filters(
			'code_snippets/export/filename',
			"{$sitename}.code-snippets.xml",
			$sitename
		) );

		return $filename;
	}

	/**
	 * Append header comments to the DOM document
	 */
	protected function do_header() {

		/* Array of translated comment lines */
		$lines = array(
			__( 'This is a code snippets export file generated by the Code Snippets WordPress plugin.', 'code-snippets' ),
			__( 'http://wordpress.org/plugins/code-snippets', 'code-snippets' ),
			__( 'To import these snippets a WordPress site follow these steps:', 'code-snippets' ),
			__( '1. Log in to that site as an administrator.', 'code-snippets' ),
			__( '2. Install the Code Snippets plugin using the directions provided at the above link.', 'code-snippets' ),
			__( "3. Go to 'Tools: Import' in the WordPress admin panel.", 'code-snippets' ),
			__( '4. Click on the "Code Snippets" importer in the list', 'code-snippets' ),
			__( '5. Upload this file using the form provided on that page.', 'code-snippets' ),
			__( '6. Code Snippets will then import all of the snippets and associated information contained in this file into your site.', 'code-snippets' ),
			__( "7. You will then have to visit the 'Snippets: Manage' admin menu and activate desired snippets.", 'code-snippets' ),
		);

		/* Add each line as a comment element */
		foreach ( $lines as $line ) {
			$comment = $this->dom->createComment( " $line " );
			$this->dom->appendChild( $comment );
		}

		/* Build a generator line, like the WordPress export files */
		$gen  = sprintf (
			'generator="Code Snippets/%s" created="%s"',
			CODE_SNIPPETS_VERSION,
			date('Y-m-d H:i')
		);

		/* Run the generator line through the standard WordPress filter */
		$type = 'code_snippets_export';
		$gen = apply_filters( "get_the_generator_$type", $gen, $type );

		/* Add it to the file as a comment */
		$gen = $this->dom->createComment( " $gen " );
		$this->dom->appendChild( $gen );
	}

	/**
	 * Render the items
	 */
	protected function do_items() {
		global $wpdb;

		/* Create the root element */
		$this->root = $this->dom->createElement( 'snippets' );
		$this->root = $this->dom->appendChild( $this->root );

		/* Loop through the snippets */
		foreach ( $this->snippet_ids as $id ) {

			/* Grab the snippet from the database */
			$snippet = $wpdb->get_row( $wpdb->prepare( "SELECT * FROM {$this->table_name} WHERE id = %d", $id ), ARRAY_A );

			/* Output the item */
			$this->do_item( $snippet );
		}
	}

	/**
	 * Append a single snippet item
	 * @param array $snippet
	 */
	protected function do_item( $snippet ) {
		$item = $this->dom->createElement( 'snippet' );
		$item = $this->root->appendChild( $item );

		foreach ( $snippet as $field_name => $field_value ) {

			/*  Don't export certain fields */
			if ( in_array( $field_name, $this->exclude_fields ) ) {
				continue;
			}

			/* Exclude this field if there is no data */
			if ( empty( $field_value ) ) {
				continue;
			}

			/* Create a new element for each field */
			$field = $this->dom->createElement( $field_name );
			$field = $item->appendChild( $field );

			/* Add the field's content */
			$value = $this->dom->createTextNode( $field_value );
			$value = $field->appendChild( $value );
		}
	}

	/**
	 * Export the snippets
	 */
	public function do_export() {

		/* Set the HTTP header */
		$filename = $this->get_filename();
		header( 'Content-Disposition: attachment; filename=' . $filename );
		header( 'Content-Type: text/xml; charset=' . get_bloginfo('charset') );

		/* Create DOM document and root element */
		$this->dom = new DOMDocument( '1.0', get_bloginfo( 'charset' ) );
		$this->dom->formatOutput = true;

		/* Add file header */
		$this->do_header();

		/* Append the snippet items */
		$this->do_items();

		/* Filter DOM document */
		apply_filters( 'code_snippets/export/dom_document', $this->dom, $this->snippet_ids, $filename );

		/* Send the document to the browser */
		echo $this->dom->saveXML();
		exit;
	}
}

endif; // class exists check
