name: "🐞 Bug Report"
description: "Did you find a bug in Code Snippets and can you reproduce it consistently? Please report it here."
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ BEFORE POSTING YOUR ISSUE
        ### 🐞 Please create GitHub issues only for Code Snippets Bug Reports. 
        #### ❌ GitHub issues should <ins>NOT BE USED FOR SUPPORT</ins> ❌.
        ❔ If you have questions, need guidance, help, or general support, please use one of the following channels:
        - 🌐 [Code Snippets Community](https://www.facebook.com/groups/codesnippetsplugin) The main Facebook group where all kinds of users come together to help each other.
        - 📄 [Documentation](https://help.codesnippets.pro/) Learn everything about our Developer-API.
        - 💡 [Feature Requests](https://roadmap.codesnippets.pro/ideas) Let us know how we can make dev-life easier for you ; )
        - 🗺️ [Roadmap](https://roadmap.codesnippets.pro/roadmap) See what we're up to.
        - ⭐ [Reviews](https://wordpress.org/plugins/code-snippets/#reviews) Please leave a review, they really make a difference for us!
        - 🔄 [Changelog](https://wordpress.org/plugins/code-snippets/#developers) Check the latest features we released.
        - 💬 [Free Support Forum](https://wordpress.org/support/plugin/code-snippets/) Get help on WordPress.org.

        💎 If you have an active [Code Snippets Pro](https://codesnippets.pro/) license you are entitled to personal support, please see your purchase email or visit your [Code Snippets Account page](https://codesnippets.pro/account/) for details.

        ### 🙏 Follow these best practices to help save you time
        - 🔍 **Search Before Posting:** Before creating a new Bug Report, please search for similar issues to prevent creating duplicates.
        - 🆕 **Stay Up-to-date:** Make sure you are using the most recent and stable versions of [Code Snippets](https://wordpress.org/plugins/code-snippets/#developers), [Code Snippets Pro](https://codesnippets.pro/), [WordPress](https://wordpress.org/download/releases/), and your theme.
        - 🔬 **Isolate the problem:** Deactivate all of your plugins (except Code Snippets Free/Pro), and temporarily change your WordPress theme to [Hello theme](https://wordpress.org/themes/hello-elementor/). If this solves the problem, gradually activate your plugins and theme one by one, until you spot the conflicting plugin or theme.
        - 🕵️ **Validate Your Issue:** If the issue can't be recreated consistently or reproduced on other sites, it's likely not a bug in Code Snippets. In that case, use one of the support links above.
        - 🧩 **Contact 3rd-party Support:** If the issue happens with a Code Snippets add-on, extension, compatible plugin, or integrated theme, contact their support first. We do not provide support for 3rd-party software.
        - 1️⃣ **One Issue Per Thread:** If you are experiencing more than one bug, submit only **<ins>ONE ISSUE PER THREAD</ins>**, so we can properly track them and reference them without any confusion.

        ## THE ISSUE
  - type: checkboxes
    id: prerequisites
    attributes:
      label: "Prerequisites"
      options:
        - label: "I have searched for similar issues in both open and closed tickets and cannot find a duplicate."
          required: true
        - label: "The issue still exists against the latest stable version of Code Snippets."
          required: true
  - type: dropdown
    id: bug_type
    attributes:
      label: "Type of Bug"
      description: "What type of bug are you reporting? Please select at least one option that is affected by the issue you're reporting (acceppts multiple options)."
      multiple: true
      options:
        - "Snippet type PHP"
        - "Snippet type HTML"
        - "Snippet type CSS"
        - "Snippet type JS"
        - "A Code Snippet"
        - "Design/Styles"
        - "Dependencies"
        - "Code Editor"
        - "Export/Import"
        - "Internationalization"
        - "Maintenance Mode"
        - "Notes"
        - "Performance"
        - "Plugin Settings"
        - "Privacy"
        - "Product/Core"
        - "Product/Pro"
        - "Product/Cloud"
        - "RTL"
        - "Semantics"
        - "SEO"
        - "UI/UX"
        - "Widget"
        - "Workflow"
        - "I'm Not Sure"
        - "Unspecified"
    validations:
      required: true
  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: "Description"
      description: "Describe the problem. What caused the issue? What did you expect to happen and what actually happened? Please be as descriptive as possible. Attach screenshots, screen recordings, and related links."
  - type: textarea
    id: steps_to_reproduce
    validations:
      required: true
    attributes:
      label: "Steps to reproduce"
      description: "List all the steps needed to reproduce the issue in detail, so we can replicate it ourselves on our own installation. Be thorough, we won't be able to reproduce it if you don't explain how."
      placeholder: "1) ... 2) ... 3) ..."
  - type: checkboxes
    id: isolating_the_problem
    attributes:
      label: "Isolating the problem"
      options:
        - label: "This bug happens with only the Code Snippets plugin active (Free or Pro)."
        - label: "This bug happens with a Blank WordPress theme active. For example: ([Hello theme](https://wordpress.org/themes/hello-elementor/))."
        - label: "I can reproduce this bug consistently following the steps above."
  - type: textarea
    id: system_info
    validations:
      required: true
    attributes:
      label: "Comment"
      description: "Please add anything else you may deem useful for us to help you."
      render: markdown
  - type: markdown
    attributes:
      value: |
        
        ---
        ⚠️ Please follow all the instructions indicated above, and fill all the required fields with valid information. We reserve the right to close issues that do not comply with these guidelines without any warning.
          
          
          
