import { Spinner } from '@wordpress/components'
import React, { useState } from 'react'
import { __, sprintf } from '@wordpress/i18n'
import { useSnippetsAPI } from '../../hooks/useSnippetsAPI'
import { createSnippetObject, getSnippetDisplayName } from '../../utils/snippets/snippets'
import { Button } from '../common/Button'
import { useSnippetForm } from '../../hooks/useSnippetForm'
import { SubmitButton } from '../common/SubmitButton'
import { Tooltip } from '../common/Tooltip'
import { ConditionEditor } from '../ConditionEditor'
import type { Snippet } from '../../types/Snippet'
import type { Dispatch, FormEventHandler, SetStateAction } from 'react'

interface ModalFooterProps {
	onClose: VoidFunction
	isSubmitting: boolean
}

const ModalFooter: React.FC<ModalFooterProps> = ({ onClose, isSubmitting }) =>
	<div className="modal-footer">
		<Button simple onClick={onClose}>
			{__('Cancel', 'code-snippets')}
		</Button>

		<div>
			{isSubmitting && <Spinner />}

			<SubmitButton primary large disabled={isSubmitting} text={__('Save Condition', 'code-snippets')} />
		</div>
	</div>

interface ModalUpperProps {
	onClose: VoidFunction
	condition: Snippet
	isSubmitting: boolean
	setCondition: Dispatch<SetStateAction<Snippet>>
}

const ModalUpper: React.FC<ModalUpperProps> = ({ onClose, condition, isSubmitting, setCondition }) =>
	<>
		<div className="modal-content-top">
			<label htmlFor="condition-name">
				{__('Condition Name', 'code-snippets')}
				<Tooltip>
					{__('Give a name to this condition so you can reuse it on other snippets, or leave blank for an autogenerated name.', 'code-snippets')}
				</Tooltip>
			</label>

			<Button simple onClick={() => onClose()}>
				{__('Apply existing condition', 'code-snippets')}
			</Button>
		</div>

		<div className="modal-content-mid">
			<input
				id="condition-name"
				type="text"
				disabled={isSubmitting}
				className="condition-title-input"
				placeholder={__('Add a name for this condition.', 'code-snippets')}
				value={condition.name}
				onChange={event => setCondition(previous => ({ ...previous, name: event.target.value }))}
			/>
		</div>
	</>

const createInitialCondition = (snippet: Snippet): Snippet =>
	createSnippetObject({
		name: '',
		tags: snippet.tags,
		scope: 'condition',
		active: false,
		conditions: {
			'_0': {
				'_0': {}
			}
		}
	})

export interface EditConditionFormProps {
	condition?: Snippet
	onClose: VoidFunction
}

export const EditConditionForm: React.FC<EditConditionFormProps> = ({ onClose, condition: initialCondition }) => {
	const api = useSnippetsAPI()
	const { snippet, setSnippet } = useSnippetForm()
	const [error, setError] = useState(false)
	const [isSubmitting, setIsSubmitting] = useState(false)
	const [condition, setCondition] = useState<Snippet>(() => initialCondition ?? createInitialCondition(snippet))

	const handleSubmit: FormEventHandler<HTMLFormElement> = event => {
		event.preventDefault()
		setIsSubmitting(true)

		const name = '' === condition.name.trim()
			// translators: %s: snippet display name.
			? sprintf(__('Condition for "%s"', 'code-snippets'), getSnippetDisplayName(snippet))
			: condition.name

		api.create({ ...condition, name })
			.then(result => {
				setSnippet(previous => ({ ...previous, conditionId: result.id }))
				setIsSubmitting(false)
				onClose()
			})
			.catch((error: unknown) => {
				console.error('Error creating condition', error)
				setIsSubmitting(false)
				setError(true)
			})
	}

	return (
		<form className="modal-form" onSubmit={handleSubmit}>
			<div className="modal-content">
				<ModalUpper
					onClose={onClose}
					condition={condition}
					isSubmitting={isSubmitting}
					setCondition={setCondition}
				/>

				<ConditionEditor condition={condition} setCondition={setCondition} />

				{error
					? <div className="notice notice-error">
						{__('An unknown error occurred. Please try again later', 'code-snippets')}
					</div>
					: null}
			</div>

			<ModalFooter
				onClose={onClose}
				isSubmitting={isSubmitting}
			/>
		</form>
	)
}
