import { Spinner } from '@wordpress/components'
import React, { useState } from 'react'
import { __, sprintf } from '@wordpress/i18n'
import { useRestAPI } from '../../hooks/useRestAPI'
import { useSnippetsList } from '../../hooks/useSnippetsList'
import { createSnippetObject, getSnippetDisplayName } from '../../utils/snippets/snippets'
import { Button } from '../common/Button'
import { useSnippetForm } from '../../hooks/useSnippetForm'
import { SubmitButton } from '../common/SubmitButton'
import { Tooltip } from '../common/Tooltip'
import { ConditionEditor } from '../ConditionEditor'
import { DismissibleNotice } from '../DismissableNotice'
import type { Snippet } from '../../types/Snippet'
import type { Dispatch, FormEventHandler, SetStateAction } from 'react'

interface ModalFooterProps {
	onClose: VoidFunction
	isSubmitting: boolean
}

const ModalFooter: React.FC<ModalFooterProps> = ({ onClose, isSubmitting }) =>
	<div className="modal-footer">
		<Button simple onClick={onClose}>
			{__('Cancel', 'code-snippets')}
		</Button>

		<div>
			{isSubmitting && <Spinner />}

			<SubmitButton primary large disabled={isSubmitting} text={__('Save Condition', 'code-snippets')} />
		</div>
	</div>

interface ModalUpperProps {
	onClose: VoidFunction
	condition: Snippet
	isSubmitting: boolean
	setCondition: Dispatch<SetStateAction<Snippet>>
}

const ModalUpper: React.FC<ModalUpperProps> = ({ onClose, condition, isSubmitting, setCondition }) =>
	<>
		<div className="modal-content-top">
			<label htmlFor="condition-name">
				{__('Condition Name', 'code-snippets')}
				<Tooltip>
					{__('Give a name to this condition so you can reuse it on other snippets, or leave blank for an autogenerated name.', 'code-snippets')}
				</Tooltip>
			</label>

			{condition.id ? null
				: <Button simple onClick={() => onClose()}>{__('Apply existing condition', 'code-snippets')}</Button>}
		</div>

		<input
			id="condition-name"
			type="text"
			disabled={isSubmitting}
			className="condition-name-input"
			placeholder={__('Add a name for this condition.', 'code-snippets')}
			value={condition.name}
			onChange={event => setCondition(previous => ({ ...previous, name: event.target.value }))}
		/>
	</>

const createInitialCondition = (snippet: Snippet): Snippet =>
	createSnippetObject({
		name: '',
		tags: snippet.tags,
		scope: 'condition',
		active: false,
		conditions: {
			_0: {
				_0: {}
			}
		}
	})

const useSubmitCondition = ({
	onSave,
	setSelectedConditionId
}: Pick<EditConditionFormProps, 'onSave' | 'setSelectedConditionId'>) => {
	const { snippetsAPI: { update } } = useRestAPI()
	const { snippet, setSnippet } = useSnippetForm()
	const { refreshSnippetsList } = useSnippetsList()

	const [isSubmitting, setIsSubmitting] = useState(false)
	const [error, setError] = useState(false)

	const submit = (condition: Snippet) => {
		setIsSubmitting(true)

		const name = '' === condition.name.trim()
			// translators: %s: snippet display name.
			? sprintf(__('Condition for "%s"', 'code-snippets'), getSnippetDisplayName(snippet))
			: condition.name

		update({ ...condition, name })
			.then(result => {
				setSnippet(previous => ({ ...previous, conditionId: result.id }))
				setIsSubmitting(false)
				setSelectedConditionId(result.id)
				refreshSnippetsList()
				onSave()
			})
			.catch((error: unknown) => {
				console.error('Error creating condition', error)
				setIsSubmitting(false)
				refreshSnippetsList()
				setError(true)
			})
	}

	return { submit, isSubmitting, error, setError }
}

export interface EditConditionFormProps {
	onSave: VoidFunction
	onCancel: VoidFunction
	condition?: Snippet
	setSelectedConditionId: Dispatch<SetStateAction<number>>
}

export const EditConditionForm: React.FC<EditConditionFormProps> = ({
	onSave,
	onCancel,
	condition: initialCondition,
	setSelectedConditionId
}) => {
	const { snippet } = useSnippetForm()
	const [condition, setCondition] = useState<Snippet>(() => initialCondition ?? createInitialCondition(snippet))
	const { submit, isSubmitting, error, setError } = useSubmitCondition({ onSave, setSelectedConditionId })

	const handleSubmit: FormEventHandler<HTMLFormElement> = event => {
		event.preventDefault()
		submit(condition)
	}

	return (
		<form className="modal-form" onSubmit={handleSubmit}>
			<div className="modal-content">
				<ModalUpper
					onClose={onCancel}
					condition={condition}
					isSubmitting={isSubmitting}
					setCondition={setCondition}
				/>

				<ConditionEditor condition={condition} setCondition={setCondition} />

				{error
					? <DismissibleNotice className="notice-error" onDismiss={() => setError(false)}>
						{__('An unknown error occurred. Please try again later', 'code-snippets')}
					</DismissibleNotice> : null}
			</div>

			<ModalFooter onClose={onCancel} isSubmitting={isSubmitting} />
		</form>
	)
}
