target: ./release.txt

variables:
  latest_commit: "git rev-list -n 1 $(git describe --tags --abbrev=0)"
  commit_log: "git diff <latest_commit> HEAD"
  diff_log: "git log <latest_commit>..HEAD"
  today: "date +%F"
  version: "jq -r .version package.json"

template: |
  = [<variables.version>] (<variables.today>) =

  __Added__
  * list of added features with issue refs 

  __Changed__
  * list of changes that already existing implementation

  __Removed__
  * optionally add this list of removed features

  __Fixed__
  * list of implemented fixes since the previous latest tag

task:
  prepare the changelog for the <variables.version> release following the template below.
  changelog sections are optional and should ONLY reflect the changes based on the commit history and provided diff.

prompt: |
  <variables.commit_log>
  ---
  <variables.diff_log>
  ---
  date is <variables.today>
  ---
  output template:
  <template>
  ---
  <task>
