import { __, sprintf } from '@wordpress/i18n'
import type { SnippetType } from '../../types/Snippet'

export interface StripResult {
	/** Code with any surrounding wrapper markup removed. */
	code: string
	/** What was taken off, already translated, or undefined if nothing was. */
	removed?: string
}

/**
 * The wrapper a snippet of each type arrives in when pasted from elsewhere.
 *
 * Snippet code is stored bare: PHP is evaluated already inside PHP, and CSS and
 * JavaScript are wrapped in their own tags when printed. Code generated by an
 * AI assistant almost always arrives wrapped in the tags for its language, and
 * often in a markdown code fence as well.
 *
 * HTML is absent on purpose: a `<style>` block in a content snippet is the
 * author's own markup, not a wrapper.
 */
const WRAPPERS: Partial<Record<SnippetType, { open: RegExp, close: RegExp, label: string }>> = {
	php: {
		// `php` is matched as a whole word so `<?phpinfo()` is left alone.
		open: /^\s*<\?(?:php\b)?/i,
		close: /\?>\s*$/,
		label: __('opening PHP tag', 'code-snippets')
	},
	css: {
		open: /^\s*<style\b[^>]*>/i,
		close: /<\/style\s*>\s*$/i,
		label: __('<style> tags', 'code-snippets')
	},
	js: {
		open: /^\s*<script\b[^>]*>/i,
		close: /<\/script\s*>\s*$/i,
		label: __('<script> tags', 'code-snippets')
	}
}

const FENCE_OPEN = /^\s*```[a-z]*[ \t]*\r?\n/i
const FENCE_CLOSE = /\r?\n\s*```\s*$/

/**
 * Remove the wrapper markup that pasted snippet code does not need.
 *
 * Mirrors `normalize_snippet_code()` in PHP, which stays in place as the safety
 * net for imports and the REST API. Doing it here as well means the editor
 * shows exactly what will be stored, rather than flagging an error for
 * something the server would quietly strip on save.
 *
 * Only a wrapper around the whole snippet is removed. Tags partway through the
 * code belong to the author.
 */
export const stripWrapperTags = (code: string, type: SnippetType): StripResult => {
	let result = code
	let fenced = false

	if (FENCE_OPEN.test(result)) {
		result = result.replace(FENCE_OPEN, '').replace(FENCE_CLOSE, '')
		fenced = true
	}

	const wrapper = WRAPPERS[type]
	const tagged = Boolean(wrapper?.open.test(result))

	if (wrapper && tagged) {
		result = result.replace(wrapper.open, '').replace(wrapper.close, '')
	}

	// Drop the line break left behind by a tag that sat on its own line.
	result = result.replace(/^\r?\n/, '')

	if (!fenced && !tagged) {
		return { code }
	}

	const removed = tagged && wrapper
		? fenced
			? sprintf(
				/* translators: %s: name of the markup that was removed, such as "opening PHP tag". */
				__('code fence and %s', 'code-snippets'),
				wrapper.label
			)
			: wrapper.label
		: __('code fence', 'code-snippets')

	return { code: result, removed }
}
