name: Build Reusable

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - name: Install dependencies
        run: |
          npm install

      - name: Build plugin
        run: npm run bundle

      - name: Upload built zip
        uses: actions/upload-artifact@v4
        with:
          name: code-snippets-${{ github.sha }}.zip
          path: bundle/code-snippets*.zip
