name: "(Release): Create Tag"

on:
  pull_request:
    types: [closed]
    branches:
      - core
      - core-beta
      - pro
      - pro-beta
jobs:
  create-tag:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Get version from package.json
        id: version
        run: |
          tag=$(jq -r .version package.json) 
          echo "tag=$tag" >> $GITHUB_OUTPUT
          echo "::info::Creating git tag [$tag]"

      - name: Create tag
        run: |
          git config user.name "code-snippets-bot"
          git config user.email "139164393+code-snippets-bot@users.noreply.github.com"
          git tag "v${{ steps.version.outputs.tag }}"
          git push origin "v${{ steps.version.outputs.tag }}"
