name: Release new developer version

on:
  workflow_dispatch:
  

jobs:
  get-release-version:
    runs-on: ubuntu-latest
    outputs:
      release-version: ${{ steps.version.outputs.version }}
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Get relese version
        id: version
        run: |
          version=$(jq -r .version package.json)
          echo $version
          echo "version=$version" >> $GITHUB_OUTPUT

  npm-run-build:
    runs-on: ubuntu-latest
    needs: get-release-version
    env:
      RELEASE_VERSION: ${{ needs.get-release-version.outputs.release-version }}
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Setup PHP
        id: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: bcmath, curl, mbstring, zip, intl, dom, fileinfo, json, iconv, pdo, pdo_mysql, tokenizer, xml, xmlreader, xmlwriter
          coverage: none
          tools: composer:v2
      
      - name: Checkout app repository
        id: checkout
        uses: actions/checkout@v3
      
      - name: Install gulp
        id: gulp-install
        shell: bash
        run: |
          npm config set registry https://registry.npmjs.org/
          npm install --global gulp-cli
      
      # - name: Pre-isntall Prism dependencies
      #   id: pre-install
      #   shell: bash
      #   run: |
      #     npm ci
      #     # curl -sL $(curl -sS  https://api.github.com/repos/PrismJS/prism-themes/releases/latest | yq .zipball_url) > prism-themes.zip
      #     # prismdir=$(unzip prism-themes.zip | grep creating | head -1 | awk '{print $2}')
      #     # npm i $prismdir

      - name: Install node dependencies
        id: yarn-install
        shell: bash
        run: |
          yarn install
      
      - name: Install composer dependencies
        id: composer-install
        shell: bash
        run: |
          composer install --no-interaction --prefer-dist --no-progress --optimize-autoloader --ignore-platform-reqs
      
      - name: Gulp bundle
        id: gulp-bundle
        shell: bash
        run: |
          gulp bundle

      - name: Create Release
        id: create-release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.RELEASE_VERSION }}
          tag_name: ${{ env.RELEASE_VERSION }}
          append_body: true
          # prerelease: false if branch is "pro" or "beta" else true
          files: |
            ./code-snippets-pro.${{ env.RELEASE_VERSION }}.zip
      
      - name: Send a notification to Slack
        id: send-notification-to-slack
        shell: bash
        run: |
          GIT_REF=$(echo ${GITHUB_REF} | cut -d / -f 3)
          echo "${GIT_REF}"
          JOB_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          echo "${JOB_URL}"
          MESSAGE="<\!channel> :rocket: *Code Snippets* \`${GIT_REF}`\ version: \`${VERSION}\` successfully relased! <${JOB_URL}|View job> | <${RELEASE_URL}|View release>\n:point_right: *<${DOWNLAOD_URL}|Download zip here>*"
          echo "${MESSAGE}"
          curl -X POST "$SLACK_WEBHOOK" \
          -H "Content-type: application/json" \
          -d "{\"type\":\"mrkdwn\",\"text\":\"${MESSAGE}\"}"
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          VERSION: ${{ env.RELEASE_VERSION }}
          RELEASE_URL: ${{ steps.create-release.outputs.url }}
          DOWNLAOD_URL: ${{ steps.create-release.outputs.upload_url }}
