name: Release new developer version

on:
  workflow_dispatch:
  

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Get relese version
        id: release-version
        run: |
          RELEASE_VERSION=$(jq -r .version package.json)
          echo $RELEASE_VERSION
          echo "version=$RELEASE_VERSION" >> $GITHUB_OUTPUT

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Setup PHP
        id: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: bcmath, curl, mbstring, zip, intl, dom, fileinfo, json, iconv, pdo, pdo_mysql, tokenizer, xml, xmlreader, xmlwriter
          coverage: none
          tools: composer:v2
      
      - name: Checkout app repository
        id: checkout
        uses: actions/checkout@v3
      
      - name: Install gulp
        id: gulp-install
        shell: bash
        run: |
          npm config set registry https://registry.npmjs.org/
          npm install --global gulp-cli
      
      # - name: Pre-isntall Prism dependencies
      #   id: pre-install
      #   shell: bash
      #   run: |
      #     npm ci
      #     # curl -sL $(curl -sS  https://api.github.com/repos/PrismJS/prism-themes/releases/latest | yq .zipball_url) > prism-themes.zip
      #     # prismdir=$(unzip prism-themes.zip | grep creating | head -1 | awk '{print $2}')
      #     # npm i $prismdir

      - name: Install node dependencies
        id: yarn-install
        shell: bash
        run: |
          yarn install
      
      - name: Install composer dependencies
        id: composer-install
        shell: bash
        run: |
          composer install --no-interaction --prefer-dist --no-progress --optimize-autoloader --ignore-platform-reqs
      
      - name: Gulp bundle
        id: gulp-bundle
        shell: bash
        run: |
          gulp bundle

      - name: Create Release
        id: create-release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.release-version.outputs.version }}
          tag_name: ${{ steps.release-version.outputs.version }}
          append_body: true
          # prerelease: false if branch is "pro" or "beta" else true
          files: |
            ./code-snippets-pro.${{ steps.release-version.outputs.version }}.zip
      
      - name: Send a notification to Slack
        id: send-notification-to-slack
        shell: bash
        run: |
          GIT_REF=$(echo ${GITHUB_REF} | cut -d / -f 3)
          echo "${GIT_REF}"
          JOB_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          echo "${JOB_URL}"
          touch slack-message
          echo -n '<!channel> :rocket: *Code Snippets* `' >> slack-message
          echo -n ${GIT_REF} >> slack-message
          echo -n '` version: `' >> slack-message
          echo -n ${RELEASE_VERSION} >> slack-message
          echo -n '` successfully relased! ' >> slack-message
          echo -n "<${JOB_URL}|View job> | <${RELEASE_URL}|View release>\n" >> slack-message
          echo -n ":point_right: *<${DOWNLOAD_URL}|Download zip here>*" >> slack-message
          MESSAGE=$(cat slack-message)
          echo "${MESSAGE}"
          curl -sS -X POST "$SLACK_WEBHOOK" \
          -H "Content-type: application/json" \
          -d "{\"type\":\"mrkdwn\",\"text\":\"${MESSAGE}\"}"
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          RELEASE_VERSION: ${{ steps.release-version.outputs.version }}
          RELEASE_URL: ${{ steps.create-release.outputs.url }}
          DOWNLOAD_URL: ${{ steps.create-release.outputs.upload_url }}
