name: Build for Pull Request

on:
  pull_request:
    types: [labeled]

jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'build')
    uses: ./.github/workflows/build.yml
    with:
      ref:
    
  upload:
