name: Build for Pull Request

on:
  pull_request:
    types: [labeled]

jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'build')
    uses: ./.github/workflows/build.yml
    with:
      ref: ${{ github.head_ref }}

  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download built zip
        uses: actions/download-artifact@v4
        with:
          name: code-snippets-${{ github.sha }}.zip
          path: ./dist

      - name: Upload PR artifact
        uses: actions/upload-artifact@v4
        with:
          name: code-snippets-pr-${{ github.sha }}.zip
          path: ./dist/code-snippets-*.zip
