name: SVN Push

description: 'Deploy plugin to WordPress.org SVN'

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Set up SVN
        run: sudo apt-get update && sudo apt-get install -y subversion

      - name: Prepare SVN credentials
        env:
          SVN_USERNAME: ${{ secrets.WP_SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.WP_SVN_PASSWORD }}
        run: |
          if [ -z "$SVN_USERNAME" ] || [ -z "$SVN_PASSWORD" ]; then
            echo "SVN credentials not set."
            exit 1
          fi

      - name: Deploy to WordPress.org SVN
        env:
          SVN_USERNAME: ${{ secrets.WP_SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.WP_SVN_PASSWORD }}
        run: |
          # Set up variables
          PLUGIN_SLUG="code-snippets"
          SVN_URL="https://plugins.svn.wordpress.org/$PLUGIN_SLUG"
          SVN_DIR="/tmp/$PLUGIN_SLUG-svn"
          ZIP_PATH="bundle/code-snippets*.zip"

          # Checkout SVN repo
          svn checkout --depth immediates $SVN_URL $SVN_DIR
          cd $SVN_DIR
          svn update trunk tags

          # Unzip build into trunk
          rm -rf trunk/*
          unzip -o $GITHUB_WORKSPACE/$ZIP_PATH -d trunk

          # SVN add/rm
          svn add --force trunk/*
          svn status | grep '^!' | awk '{print $2}' | xargs -r svn rm --force

          # Commit trunk
          svn commit -m "Deploy trunk for ${{ inputs.ref }}" --username "$SVN_USERNAME" --password "$SVN_PASSWORD" --no-auth-cache --non-interactive

          # Tag release
          svn copy trunk tags/${{ inputs.ref }}
          svn commit -m "Tag ${{ inputs.ref }}" tags/${{ inputs.ref }} --username "$SVN_USERNAME" --password "$SVN_PASSWORD" --no-auth-cache --non-interactive
